{% set name = "types-filelock" %}
{% set version = "3.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-filelock-{{ version }}.tar.gz
  sha256: 6bdc70d4c210046b8a6edecfd6d370f7c9e52996da772713b7971f453d6c18d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/filelock-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for filelock
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
